site_name: Analysis of flow cytometry data with R
nav:
    - Home: index.md
    - Intro to R :
      - Course schedule: introR/course_schedule.md
      - Precourse preparations: introR/precourse.md
      - Material: introR/material.md  
      - Day 1:
        -  Exercises: introR/day1/exercises_d1.md
      - Day 2:
        - Exercises: introR/day2/exercises_d2.md  
      - Useful links: introR/links.md  
    - Flow cytometry analysis:
      - Course schedule: flowCyt/course_schedule.md
      - Precourse preparations: flowCyt/precourse.md
      - Material: flowCyt/material.md  
      - Day 1:
        - Exercises: flowCyt/day1/exercises_d1.md
      - Day 2:
        - Exercises: flowCyt/day2/exercises_d2.md 
      - Day 3:
        - Exercises: flowCyt/day3/exercises_d3.md
      - Day 4:
        - Exercises: flowCyt/day4/exercises_d4.md
      - Day 5:
        - Exercises: flowCyt/day5/exercises_d5.md
      - Useful links: flowCyt/links.md  

   
theme:
  name: material
  logo: assets/images/TDS_logo.svg
  favicon: assets/images/TDS_logo.svg

# Repository
repo_name: taniawyss/flow-cytometry-analysis-with-R
repo_url: https://github.com/taniawyss/flow-cytometry-analysis-with-R

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
